[tool.poetry]
name = "projeto-do-zero-hero"
version = "0.1.0"
description = "meu projeto de etl"
authors = ["wallace"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
pandas = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
